### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by KarimJedda** [arieb/python-testdata#7]
Hello, is this project still active? Should I use another library? Do you need support?

**Comment by arieb** [comment]
Hey,
I don't really have time to maintain it, but if you submit pull requests ill try my best to merge them in.
using this library is up to you :)

**Comment by nhoening** [comment]
Not advising on what to do, but there is an active fork: https://github.com/psafont/fake-gen

**Comment by KarimJedda** [comment]
Thanks for the heads up @nhoening :)
